logging:
  config: classpath:logback-spring.xml

verification:
  code-length: ${VERIFICATION_CODE_LENGTH}
  ttl: ${VERIFICATION_TTL}

spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_TIMEOUT}